header = """
/* ffi Header */

#ifdef __cplusplus
extern "C" {
#endif
"""
trailer = """
#ifdef __cplusplus
} /* extern "C" */
#endif
"""

include_guard = "FFI_H"
include_version = true
language = "C"

[parse]
parse_deps = true
include = ["ffi-toolkit"]

[enum]
prefix_with_name = true
